return function()
    local Bag = require(script.Parent)

    describe("bag", function()
		it("should create a new bag", function()
			local bag = Bag.new()
			expect(bag).to.be.ok()
			expect(bag.className).to.equal("Bag")
		end)
		it("should destroy the bag", function()
			local bag = Bag.new()
			bag:destroy()
			expect(bag._items).never.to.be.ok()
		end)
		it("should add an object to the bag", function()
			local bag = Bag.new()
			local part = Instance.new("Part")
			bag:add(part)
			expect(#bag._items).to.be.equal(1)
		end)
		it("should remove an object from the bag", function()
			local bag = Bag.new()
			local part = Instance.new("Part")
			bag:add(part)
			bag:remove(part)
			expect(#bag._items).to.be.equal(0)
		end)
		it("should dispose of the bag", function()
			local bag = Bag.new()
			local part = Instance.new("Part")
			bag:add(part)
			expect(#bag._items).to.be.equal(1)
			bag:dispose()
			expect(#bag._items).to.be.equal(0)
		end)
		it("should dispose of the bag and all objects in it", function()
			local bag = Bag.new()
			local part = Instance.new("Part")
			local connection = part.Touched:Connect(function() end)
			bag:add(part)
			bag:add(connection)
			expect(#bag._items).to.be.equal(2)
			bag:dispose()
			expect(#bag._items).to.be.equal(0)
		end)
		it("should dispose of the bag and all objects in it when destroyed", function()
			local bag = Bag.new()
			local part = Instance.new("Part")
			local connection = part.Touched:Connect(function() end)
			bag:add(part)
			bag:add(connection)
			expect(#bag._items).to.be.equal(2)
			bag:destroy()
			expect(bag._items).never.to.be.ok()
		end)
		it("should dispose of the bag and all objects in it when destroyed with a custom dispose method", function()
			local bag = Bag.new()
			local fired = false
			local table = {
				custom = function(self)
					fired = true
				end
			}
			bag:add(table, "custom")
			bag:destroy()
			expect(fired).to.be.equal(true)
		end)
		it("should destroy the bag when the instance it's attached to is destroyed", function()
			local bag = Bag.new()
			local part = Instance.new("Part")
			part.Parent = workspace
			bag:attach(part)

			local disposed = false
			bag:add(function()
				disposed = true
			end)

			expect(bag._items).to.be.ok()
			part:Destroy()

			task.defer(function()
				expect(disposed).to.be.equal(true)
				expect(bag._items).never.to.be.ok()
			end)
		end)
    end)
end