return function()
    local Event = require(script.Parent)

    describe("Event", function()
		it("Should create a new event", function()
			local event = Event.new()
			expect(event).to.be.ok()
			expect(event.className).to.equal("Event")
		end)
		it("Should fire the event", function()
			local event = Event.new()
			local fired = false
			event:Connect(function(args)
				fired = true
			end)
			event:Fire()
			task.defer(function()
				expect(fired).to.equal(true)
			end)
		end)
		it("Should fire the event with a value", function()
			local event = Event.new()
			local fired
			event:Connect(function(value)
				fired = value
			end)
			event:Fire("Hello, world!")
			task.defer(function()
				expect(fired).to.equal("Hello, world!")
			end)
		end)
		it("Should wait for the event to fire", function()
			local event = Event.new()
			local fired = false
			task.spawn(function()
				fired = event:Wait()
			end)
			expect(fired).to.equal(false)
			task.delay(0.1, function()
				event:Fire(true)
				expect(fired).to.equal(true)
			end)
		end)
		it("Should timeout when waiting for the event", function()
			local event = Event.new()
			local fired = event:Wait(0.1)
			expect(fired).to.equal(nil)
			task.spawn(function()
				fired = event:Wait(0.2)
				expect(fired).to.equal(123)
			end)
			event:Fire(123)
		end)
		it("Should disconnect the event", function()
			local event = Event.new()
			local fired = false
			local connection = event:Connect(function()
				fired = true
			end)
			connection:Disconnect()
			event:Fire()
			expect(fired).to.equal(false)
		end)
		it("Should destroy the event", function()
			local event = Event.new()
			event:Destroy()
			task.defer(function()
				expect(event._connections).never.to.be.ok()
				expect(event._callbacks).never.to.be.ok()
				expect(event._values).never.to.be.ok()
			end)
		end)
		it("Should connect once", function()
			local event = Event.new()
			local count = 0
			event:Once(function()
				count += 1
			end)
			event:Fire()
			event:Fire()
			task.defer(function()
				expect(count).to.equal(1)
			end)
		end)
		it("Should disconnect all connections", function()
			local event = Event.new()
			local fired = false
			event:Connect(function()
				fired = true
			end)
			event:DisconnectAll()
			event:Fire()
			expect(fired).to.equal(false)
		end)
    end)
end